name: Update README with Total Commits

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with Write Access
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch Total Commits
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
        run: |
          chmod +x scripts/commits-counter.sh
          ./scripts/commits-counter.sh

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.README_TOKEN }}@github.com/florann/florann.git
          git add README.md
          git commit -m "Update commit count in README"
          git push origin main